### ISSUE TITLE
OAuthAccessTokenActivity

### ISSUE THREAD

**Issue by CBarbas** [ddewaele/AndroidTwitterGoogleApiJavaClient#1]
Good day

This is exactly what I was looking for!!!
Now when I load the project from github repository as far as I see at problems report, I have something wrong with the Google APIs Client Library for Java, I have download the library but I don't the steps after.

Thanks
Christopher

**Comment by ddewaele** [comment]
You should import the project as a maven project in Eclipse ADT. No need to download the dependencies yourself. Updated the docs.
